# Site settings
title: Hello, Unknown
description: Mika's Uncharted Log
baseurl: "" # 서브패스가 있다면 입력 (예: "/blog")
url: "https://mik-a-ela.github.io"

# Build settings
markdown: kramdown
highlighter: rouge

# Permalink
permalink: /:categories/:title/

# Collections for categories
collections:
  bridge:
    output: true
    permalink: /bridge/:title/
  insight:
    output: true
    permalink: /insight/:title/
  lab:
    output: true
    permalink: /lab/:title/
  log:
    output: true
    permalink: /log/:title/

# Default values
defaults:
  - scope:
      path: ""
      type: "bridge"
    values:
      layout: "post"
      category: "Bridge"
  - scope:
      path: ""
      type: "insight"
    values:
      layout: "post"
      category: "Insight"
  - scope:
      path: ""
      type: "lab"
    values:
      layout: "post"
      category: "Lab"
  - scope:
      path: ""
      type: "log"
    values:
      layout: "post"
      category: "Log"

# Navigation
navigation:
  - title: Bridge
    url: /bridge/
    description: About Me
  - title: Insight
    url: /insight/
    description: Study
  - title: Lab
    url: /lab/
    description: Mini Project
  - title: Log
    url: /log/
    description: Trial & Error
