# Site settings
title: Hello, Unknown
description: Mika's Uncharted Log
baseurl: ""
url: "https://mik-a-ela.github.io"

# Build settings
markdown: kramdown
highlighter: rouge

# IMPORTANT: 미래 날짜 포스트 허용
future: true

# Permalink
permalink: /:categories/:title/

# Default values for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Navigation
navigation:
  - title: Bridge
    url: /bridge/
    description: About Me
  - title: Insight
    url: /insight/
    description: Study
  - title: Lab
    url: /lab/
    description: Mini Project
  - title: Log
    url: /log/
    description: Trial & Error
